services:
  - type: web
    name: chatme
    env: node
    branch: main
    rootDir: .
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
